spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
         "[spring.json.type.mapping]": foo:ru.strebkov.t1_Excample_Kafka.model.Foo1, bar:ru.strebkov.t1_Excample_Kafka.model.Bar1
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
server:
  port: 7878